-- Database: UsersDB

-- DROP DATABASE IF EXISTS "UsersDB";

CREATE DATABASE "UsersDB"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Latin America.1252'
    LC_CTYPE = 'Spanish_Latin America.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	CREATE TABLE Usuarios (
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO1 VARCHAR(255) NOT NULL,
    APELLIDO2 VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    UNIVERSIDAD VARCHAR(255) NOT NULL,
    CARNET VARCHAR(255) NOT NULL,
    ROL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);